version: "3.7"
services:
  flask:
    image: pom_back
    build:  ./backend
    ports:
      - "5000:5000"
    env_file:
      - dev.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  angular:
    image: pom_front
    build: ./frontend
    ports:
      - "4200:80"