"""phase_model_boolean - delete

Revision ID: 1b063752380c
Revises: 8d7c35336d5e
Create Date: 2022-11-03 09:03:14.845180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b063752380c'
down_revision = '8d7c35336d5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directory_of_outlay_class')
    op.drop_column('directory_of_order', 'phase_1_model')
    op.drop_column('directory_of_order', 'phase_2_model')
    op.drop_column('directory_of_order', 'phase_3_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory_of_order', sa.Column('phase_3_model', postgresql.ARRAY(sa.BOOLEAN()), autoincrement=False, nullable=True))
    op.add_column('directory_of_order', sa.Column('phase_2_model', postgresql.ARRAY(sa.BOOLEAN()), autoincrement=False, nullable=True))
    op.add_column('directory_of_order', sa.Column('phase_1_model', postgresql.ARRAY(sa.BOOLEAN()), autoincrement=False, nullable=True))
    op.create_table('directory_of_outlay_class',
    sa.Column('id_outlay_class', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('outlay_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_outlay_class', name='directory_of_outlay_class_pkey')
    )
    # ### end Alembic commands ###
