"""initdb

Revision ID: 5715fd2ae454
Revises: 1b063752380c
Create Date: 2023-01-16 07:49:34.647561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5715fd2ae454'
down_revision = '1b063752380c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directory_of_order', 'data_send_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory_of_order', sa.Column('data_send_order', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
